version: "3.8"

services:
    postgresql:
        image: postgres:16.1
        ports:
            - 5432:5432
        expose:
            - 5432
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: calmx
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "admin", "-d", "calmx"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - calmx
        container_name: postgresql

    liquibase:
        image: liquibase/liquibase:4.25
        volumes:
            - ./scripts/db/config/db.changelog-0.0.1.xml:/liquibase/config/db.changelog-0.0.1.xml
            - ./scripts/db/changesets/:/liquibase/changesets/
            - ./scripts/db/config/liquibase.properties:/liquibase/liquibase.properties
        command: --defaults-file='liquibase.properties' update
        networks:
            - calmx
        container_name: liquibase
        depends_on:
            postgresql:
                condition: service_healthy

networks:
    calmx:
        name: calmx
